// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc812.BB9.subsystems;

import org.usfirst.frc812.BB9.Robot;
import org.usfirst.frc812.BB9.RobotMap;
import org.usfirst.frc812.BB9.commands.*;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.drive.MecanumDrive;


/**
 *
 */
public class DriveTrain extends Subsystem {

	public double lastX, lastY, lastRotate;
	public boolean motionlock = false;
	
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
//   private final DifferentialDrive robotDrive = RobotMap.dtProductionRobotDrive;
   private final MecanumDrive robotDrive = RobotMap.dtMecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void takeJoystickInputs(XboxController xbc) {
    	
    	lastX = powerTrim(xbc.getRawAxis(4)); // right xbox joystick X axis (strafe left, right)
    	lastY = -powerTrim(xbc.getRawAxis(5)); // right xbox joystick Y axis (fwd, back)
    	lastRotate = powerTrim(xbc.getRawAxis(0)); // left xbox joystick X axis
    	
//    	System.out.println("lastx=" + lastX + " lastY=" + lastY + " lastRotate=" + lastRotate);
    	robotDrive.driveCartesian(lastX, lastY, lastRotate);
//    	robotDrive.arcadeDrive(right.getY(), -right.getX(), true);
    }

    public double powerTrim(double value) {
 
    	if( value >= 0.5) {
    		return(0.5);
    	} else if( value <= -0.5) {
    		return(-0.5);
    	} else {
    		return(value);
    	}
    }

	public void stop() {
    	//robotDrive.drive(0,0);
    	
    	System.out.println(">>>>>> Stop");
//    	robotDrive.arcadeDrive(0,0,false);
    	robotDrive.driveCartesian(0, 0, 0);
//    	motionlock = true;
    }
    
    public void start() {
    	
    	System.out.println("<<<<<<< Start");
//    	if(motionlock == false){
//        	robotDrive.arcadeDrive(0, 0, true);
//    	}
//    	else{
//    		motionlock = false;
//    	}
    }
    

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    	setDefaultCommand(new DriveWithJoysticks());
    }

	public void drive(double accel, int i) {
		// TODO Auto-generated method stub
		
	}
}

