// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc812.BB9;

import edu.wpi.first.wpilibj.TimedRobot;
//import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.networktables.NetworkTable;

import org.usfirst.frc812.BB9.commands.AutonomousCommand;
import org.usfirst.frc812.BB9.subsystems.ArmDriveMotorSubsystem;
import org.usfirst.frc812.BB9.subsystems.BallGatheringSubsystem;
import org.usfirst.frc812.BB9.subsystems.ControlBoxSubsystem2019;
import org.usfirst.frc812.BB9.subsystems.DriveTrain;
import org.usfirst.frc812.BB9.subsystems.DrivelineSubsystem;
import org.usfirst.frc812.BB9.subsystems.HatchSubsystem;
import org.usfirst.frc812.BB9.subsystems.PistonLiftSubsystem;
import org.usfirst.frc812.BB9.RobotMap;


/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends TimedRobot {

	Command autonomousCommand;

	public static OI oi;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static DriveTrain driveTrain;
	public static ControlBoxSubsystem2019 controlBoxSubsystem;
	public static DrivelineSubsystem drivelineSubsystem;
	public static ArmDriveMotorSubsystem armDriveMotorSubsystem;
	public static BallGatheringSubsystem ballGatheringSubsystem;
	public static HatchSubsystem hatchSubsystem;
	public static PistonLiftSubsystem pistonLiftSubsystem;

	public static String gameData;
	public static boolean runOnce;
	
	public static double centerX = 3.14;
//	private RobotDrive drive;

	private static final double shift_up_speed = 700; //feet pers sec
	private static final double shift_down_speed = 600 ; //feet per sec
	private boolean isInHighGear;
	public static int shift_control;
	public static boolean quick_turn;
	public static NetworkTable nttable;
	private int loopCounter;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	/**
	 * This function is run when the robot is first started up and should be
	 * used for any initialization code.
	 */
	public void robotInit() {

		NetworkTableInstance ntinst = NetworkTableInstance.getDefault();
		nttable = ntinst.getTable("0team812");

		RobotMap.init();
	
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		controlBoxSubsystem = ControlBoxSubsystem2019.getInstance();
		pistonLiftSubsystem = PistonLiftSubsystem.getInstance();
		driveTrain = new DriveTrain();
		drivelineSubsystem = new DrivelineSubsystem();
		armDriveMotorSubsystem = new ArmDriveMotorSubsystem();
		ballGatheringSubsystem = new BallGatheringSubsystem();
		hatchSubsystem = new HatchSubsystem();

		Timer.delay(0.1);
		
		// The following print statements come from the controlBoxSubsystem.. they're
		// only here for testing initial connection to the wheel  encoders while we have no
		// joysticks hooked up

		 Timer.delay(0.005);

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
		// OI must be constructed after subsystems. If the OI creates Commands
		// (which it very likely will), subsystems are not guaranteed to be
		// constructed yet. Thus, their requires() statements may grab null
		// pointers. Bad news. Don't move it.
		oi = new OI();

		// instantiate the command used for the autonomous period
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

//			setGear(true); // high gear

// Due to the top heavy nature of the 2019 bot, we're pinning the two 
// speed transmission to low gear. The buttons in OI that would shift 
// from low, to high, to auto, are commented out. So no gear changes should
// occur.
			setGear(false);	// low gear
			shift_control = 1; // initialize in low gear, not auto transmission

			loopCounter = 0;

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	}

	/**
	 * This function is called when the disabled button is hit. You can use it
	 * to reset subsystems before shutting down.
	 */
	public void disabledInit() {

	}

	public void disabledPeriodic() {
		Scheduler.getInstance().run();
	}

	public void autonomousInit() {
		// schedule the autonomous command (example)
		autonomousCommand = new AutonomousCommand();
		
		runOnce = true;
//		gameData = "RRR";
		System.out.println("auto init");
		if (autonomousCommand != null)
			autonomousCommand.start();
	}

	/**
	 * This function is called periodically during autonomous
	 */
	public void autonomousPeriodic() {
	//	System.out.println("auto running");
		Scheduler.getInstance().run();
		//System.out.println("leftcount is " +LeftCount );
		//System.out.println("rightcount is " + RightCount );
	}

	public void teleopInit() {
		// This makes sure that the autonomous stops running when
		// teleop starts running. If you want the autonomous to
		// continue until interrupted by another command, remove
		// this line or comment it out.
		if (autonomousCommand != null)
			autonomousCommand.cancel();
	}

	/**
	 * This function is called periodically during operator control
	 */
	public void teleopPeriodic() {
		double speed;
		
		Scheduler.getInstance().run();
		loopCounter += 1;
		speed=Math.max(DrivelineSubsystem.getLeftEncoder().getRate(),
						DrivelineSubsystem.getRightEncoder().getRate());
		nttable.getEntry("Robot-speed:").setNumber(speed);

		controlBoxSubsystem.readBits(); // read the switches on the external control box
		controlBoxSubsystem.printBits();

		boolean shift = false;
		nttable.getEntry("Robot-shift_control:").setNumber(shift_control);
		switch(shift_control)
		{
			case 0: // Auto
				if (isHighGear() )
				{
					shift = speed>shift_down_speed;
				} else {
					shift = speed>shift_up_speed;
				}
				break;
			case 1: // low
				shift = false; 
				break;
			case 2: // high
				shift = true;
				break;
		}
		nttable.getEntry("Robot-shift:").setBoolean(shift);
		setGear(shift);
	}

	/**
	 * This function is called periodically during test mode
	 */
	public void testPeriodic() {
	//	LiveWindow.run();
	}

	public double getCenterX() {
		return centerX;
	}

	public void setCenterX(double centerX) {
		this.centerX = centerX;
	}

    public void setGear(boolean gearValue) {
		RobotMap.shifter.set(gearValue ? Value.kForward : Value.kReverse);
		isInHighGear = gearValue;
		nttable.getEntry("isInHighGear:").setBoolean(isInHighGear);
    }

    public boolean isHighGear() {
	return isInHighGear;
    }
}
